name: Demo CI

on:
  pull_request:
    branches: [ main ]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar saludo
        run: echo "¡Hola! Esto es una ejecución automática de GitHub Actions desde un pull request."
